#!/bin/sh
#this script is used to filter-out the data generated by measure.sh and only the required average value of xy points of RGBW are extracted to filtered.csv
#a simplified filtered.csv is needed to run python script provided by imagetools repo: https://github.com/hackboxguy/imagetools.git
# Parse command line arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --input=*)
            INPUT=$(echo "$1" | sed 's/--input=//')
            shift
            ;;
        --output=*)
            OUTPUT=$(echo "$1" | sed 's/--output=//')
            shift
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

# Verify input parameters
if [ -z "$INPUT" ] || [ -z "$OUTPUT" ]; then
    echo "Usage: $0 --input=<input_csv> --output=<output_csv>"
    exit 1
fi

# Check if input file exists
if [ ! -f "$INPUT" ]; then
    echo "Input file $INPUT does not exist"
    exit 1
fi

# Process the CSV and calculate averages using awk
awk -F',' '
BEGIN {
    # Initialize counters and sums for each color
    colors["W"] = colors["R"] = colors["G"] = colors["B"] = 0
    # Define color order
    color_order[1] = "R"
    color_order[2] = "G"
    color_order[3] = "B"
    color_order[4] = "W"
    num_colors = 4
}

# Function to check if a value is valid number
function is_valid(val) {
    return val != "" && val ~ /^[0-9]*\.?[0-9]+$/
}

# Skip header
NR > 1 {
    color = $4   # Sampled-Color column
    x = $9       # x coordinate
    y = $10      # y coordinate
    Y = $8       # Y (luminance) value
    
    # Only add values if all required fields are valid numbers
    if (is_valid(x) && is_valid(y) && is_valid(Y)) {
        sum_x[color] += x
        sum_y[color] += y
        sum_Y[color] += Y
        count[color]++
    } else if (color != "") {
        print "Warning: Skipping incomplete data for " color " at line " NR > "/dev/stderr"
    }
}

END {
    # Print header to output file
    print "Color,x,y,Y" > "'$OUTPUT'"
    
    # Print colors in specified order
    for (i = 1; i <= num_colors; i++) {
        color = color_order[i]
        if (count[color] > 0) {
            avg_x = sum_x[color] / count[color]
            avg_y = sum_y[color] / count[color]
            avg_Y = sum_Y[color] / count[color]
            # Build output string piece by piece
            out = color
            out = out "," sprintf("%.4f", avg_x)
            out = out "," sprintf("%.4f", avg_y)
            out = out "," sprintf("%.3f", avg_Y)
            print out >> "'$OUTPUT'"
            print "Info: " color " color averaged from " count[color] " samples" > "/dev/stderr"
        } else {
            print "Warning: No valid data found for " color > "/dev/stderr"
        }
    }
}' "$INPUT"

rc=$?
if [ $rc -eq 0 ]; then
    echo "Successfully processed data and wrote to $OUTPUT"
else
    echo "Error processing data"
    exit 1
fi
